### ISSUE TITLE
Hide output in console when playing video

### ISSUE THREAD

**Issue by KenDingel** [ysdragon/StreamBot#1]
Using your example script, I get an output in the console like this. Is there a way to hide this?

```
28 902 video
3 1699 audio
13 1700 audio
38.66666666666424 903 video
17 1701 audio
20 1702 audio
33.33333333332848 904 video
5 1703 audio
14 1704 audio
19 1705 audio
41 905 video
13 1706 audio
19 1707 audio
39.66666666666424 906 video
18 1708 audio
14 1709 audio
41.33333333332848 907 video
```

**Comment by ysdragon** [comment]
Try to comment out any console.log i.e [line 352](https://github.com/ysdragon/StreamBot/blob/2d0fb41111470ba545570d8d4ae5390c5d946fd6/src/index.ts#L352)
