### ISSUE TITLE
Intents error (Windows)

### ISSUE THREAD

**Issue by anlekg** [ysdragon/StreamBot#12]
Hi ! I'm getting an Intent error on Windows while loading the bot :  
![image](https://github.com/ysdragon/StreamBot/assets/106981899/dcf67428-7aa2-4554-9d24-8ce980f85d43)
![image](https://github.com/ysdragon/StreamBot/assets/106981899/826df963-2ed3-44cd-9310-527db27763ed)
All intents are enable... i tried to add intents to index.ts and rebuild but without success : 
![image](https://github.com/ysdragon/StreamBot/assets/106981899/d23ff633-f6ba-45a5-a017-7749f1089af4)
any ideas ?

**Comment by TheSavageTaco** [comment]
I'm running into the same issue, Ubuntu 22.04.3 LTS fresh install

**Comment by ysdragon** [comment]
I will check it!

**Comment by ysdragon** [comment]
I have noticed that you are using a Discord bot token. You should use a regular Discord user token. You can follow the steps outlined in the README.

**Comment by ysdragon** [comment]
Closed as resolved!
