### ISSUE TITLE
problem with npm i

### ISSUE THREAD

**Issue by fightersabo** [ysdragon/StreamBot#16]
root@discordbotlive:~/StreamBot# npm i
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: @dank074/discord-video-stream@3.0.5
npm ERR! Found: discord.js-selfbot-v13@3.1.4
npm ERR! node_modules/discord.js-selfbot-v13
npm ERR!   discord.js-selfbot-v13@"^3.1.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer discord.js-selfbot-v13@"2.x" from @dank074/discord-video-stream@3.0.5
npm ERR! node_modules/@dank074/discord-video-stream
npm ERR!   @dank074/discord-video-stream@"^3.0.5" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: discord.js-selfbot-v13@2.15.1
npm ERR! node_modules/discord.js-selfbot-v13
npm ERR!   peer discord.js-selfbot-v13@"2.x" from @dank074/discord-video-stream@3.0.5
npm ERR!   node_modules/@dank074/discord-video-stream
npm ERR!     @dank074/discord-video-stream@"^3.0.5" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! /root/.npm/_logs/2024-02-08T10_34_18_071Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: /root/.npm/_logs/2024-02-08T10_34_18_071Z-debug-0.log

**Comment by ysdragon** [comment]
Please remove node_modules and run npm i again!
