### ISSUE TITLE
Error: Build failed on windows 

### ISSUE THREAD

**Issue by B3-design** [ysdragon/StreamBot#2]
npm WARN deprecated string-similarity@4.0.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated node-opus@0.3.3: This project is unmaintained. See @discordjs/opus for an alternative.
npm WARN cleanup Failed to remove some directories [
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\asimv\\Desktop\\DiscordStreamVideoBot-main\\node_modules\\ffmpeg-static',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\asimv\Desktop\DiscordStreamVideoBot-main\node_modules\ffmpeg-static'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\asimv\\Desktop\\DiscordStreamVideoBot-main\\node_modules\\ffmpeg-static'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\asimv\\Desktop\\DiscordStreamVideoBot-main\\node_modules\\@discordjs\\opus',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\asimv\Desktop\DiscordStreamVideoBot-main\node_modules\@discordjs\opus'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\asimv\\Desktop\\DiscordStreamVideoBot-main\\node_modules\\@discordjs\\opus'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\asimv\\Desktop\\DiscordStreamVideoBot-main\\node_modules\\@discordjs',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\asimv\Desktop\DiscordStreamVideoBot-main\node_modules\@discordjs\opus'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\asimv\\Desktop\\DiscordStreamVideoBot-main\\node_modules\\@discordjs\\opus'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\asimv\\Desktop\\DiscordStreamVideoBot-main\\node_modules',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\asimv\Desktop\DiscordStreamVideoBot-main\node_modules\ffmpeg-static'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\asimv\\Desktop\\DiscordStreamVideoBot-main\\node_modules\\ffmpeg-static'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\asimv\\Desktop\\DiscordStreamVideoBot-main\\node_modules\\@dank074\\discord-video-stream',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\asimv\Desktop\DiscordStreamVideoBot-main\node_modules\@dank074\discord-video-stream\node_modules\@discordjs\opus'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\asimv\\Desktop\\DiscordStreamVideoBot-main\\node_modules\\@dank074\\discord-video-stream\\node_modules\\@discordjs\\opus'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\asimv\\Desktop\\DiscordStreamVideoBot-main\\node_modules\\@dank074',
npm WARN cleanup     [Error: EBUSY: resource busy or locked, rmdir 'C:\Users\asimv\Desktop\DiscordStreamVideoBot-main\node_modules\@dank074\discord-video-stream\node_modules\@discordjs\opus'] {
npm WARN cleanup       errno: -4082,
npm WARN cleanup       code: 'EBUSY',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\asimv\\Desktop\\DiscordStreamVideoBot-main\\node_modules\\@dank074\\discord-video-stream\\node_modules\\@discordjs\\opus'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\asimv\\Desktop\\DiscordStreamVideoBot-main\\node_modules\\discord-api-types',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\asimv\Desktop\DiscordStreamVideoBot-main\node_modules\discord-api-types\payloads\v8'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\asimv\\Desktop\\DiscordStreamVideoBot-main\\node_modules\\discord-api-types\\payloads\\v8'
npm WARN cleanup     }
npm WARN cleanup   ],
npm WARN cleanup   [
npm WARN cleanup     'C:\\Users\\asimv\\Desktop\\DiscordStreamVideoBot-main\\node_modules\\@discordjs\\formatters',
npm WARN cleanup     [Error: EPERM: operation not permitted, rmdir 'C:\Users\asimv\Desktop\DiscordStreamVideoBot-main\node_modules\@discordjs\formatters'] {
npm WARN cleanup       errno: -4048,
npm WARN cleanup       code: 'EPERM',
npm WARN cleanup       syscall: 'rmdir',
npm WARN cleanup       path: 'C:\\Users\\asimv\\Desktop\\DiscordStreamVideoBot-main\\node_modules\\@discordjs\\formatters'
npm WARN cleanup     }
npm WARN cleanup   ]
npm WARN cleanup ]
npm ERR! code 1
npm ERR! path C:\Users\asimv\Desktop\DiscordStreamVideoBot-main\node_modules\node-opus
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node-gyp rebuild
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.4.0
npm ERR! gyp info using node@18.18.0 | win32 | x64
npm ERR! gyp info find Python using Python version 3.10.11 found at "C:\Users\asimv\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\python.exe"
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS msvs_version not set from command line or npm config
npm ERR! gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
npm ERR! gyp ERR! find VS could not use PowerShell to find Visual Studio 2017 or newer, try re-running with '--loglevel silly' for more details
npm ERR! gyp ERR! find VS looking for Visual Studio 2015
npm ERR! gyp ERR! find VS - not found
npm ERR! gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
npm ERR! gyp ERR! find VS **************************************************************
npm ERR! gyp ERR! find VS
npm ERR! gyp ERR! configure error
npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:380:14)
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:401:16
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:430:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:517:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1098:16)
npm ERR! gyp ERR! System Windows_NT 10.0.22621
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd C:\Users\asimv\Desktop\DiscordStreamVideoBot-main\node_modules\node-opus
npm ERR! gyp ERR! node -v v18.18.0
npm ERR! gyp ERR! node-gyp -v v9.4.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in: C:\Users\asimv\AppData\Local\npm-cache\_logs\2023-10-08T19_43_19_633Z-debug-0.log

**Comment by ysdragon** [comment]
Can you try to install windows build tools `npm install --global windows-build-tools@4.0.0` and try again?

**Comment by B3-design** [comment]
Bro not work  تجي دسكورد ياباشا bootnet

في اثنين، ٩ أكتوبر، ٢٠٢٣ في ١٠:٣١ م، كتب DraGoN ***@***.***>:

**Comment by ysdragon** [comment]
Yes, you can add me `ysdragon`.

**Comment by Fahkry** [comment]
> Yes, you can add me `ysdragon`.

i send you invite my name fakhry

**Comment by ysdragon** [comment]
Accepted.
