### ISSUE TITLE
Invalid Intents

### ISSUE THREAD

**Issue by SuperiorWes** [ysdragon/StreamBot#20]
Trying to figure this out, this seems to be the only bot that exists that can do this. Seeing multiple posts about how this isn't even possible, yet you have it here and there are people posting "bugs" etc. 

Either way, I dont know shit about code etc. But I managed to get far enough to the point where I get 'INVALID_INTENTS', I see a few posts about it here and there but it just leads to more errors.

**Comment by ysdragon** [comment]
Duplicated issue, please check this issue #12
