### ISSUE TITLE
Can't build 1.0.5

### ISSUE THREAD

**Issue by OuterWinnie** [ysdragon/StreamBot#23]
I get this error when trying to build, any ideas?

![imagen](https://github.com/ysdragon/StreamBot/assets/6392320/9fd04f3e-5117-4738-a3dc-d693effbd264)

**Comment by ysdragon** [comment]
When I released it, there was no problem when building, I will check again.

**Comment by ysdragon** [comment]
Fixed here [c57d8ac](https://github.com/ysdragon/StreamBot/commit/c57d8ac719a0c7b6fe4081f3c5abca78e01f6023)
