### ISSUE TITLE
Discord limits

### ISSUE THREAD

**Issue by drizzt09** [ysdragon/StreamBot#27]
Voice channels in discord has a 50 member limit. Does this bypass that limit to watch the stream and text chat?
Trying to mirror Facebook groups where we can easily get over 1000 viewers.

**Comment by ysdragon** [comment]
No, this doesn't bypass anything.

**Comment by drizzt09** [comment]
I guess my question really should be better put.

When this is used does it require a voice/share channel or can it go to a normal chat/forum channel?

Voice/share channels have a limit.
Chat/forum channels do not.

If I play a video and share screen natively it must be in a voice/share channel. Therefore I am limited to how many members can connect. 

If your app allows to play video in a non-voice/share channel I won't be limited.

**Comment by ysdragon** [comment]
Nope, you can only stream to a voice channel.

**Comment by ysdragon** [comment]
You can try to implement your solution to make it stream to Facebook groups as you said before.

**Comment by drizzt09** [comment]
No I am trying to move from FB Groups but the 50 member limit in voice channels is why I have not made this move though.
