### ISSUE TITLE
Errors when running `bun run build` on a brand new install

### ISSUE THREAD

**Issue by nexxai** [ysdragon/StreamBot#36]
After cloning the repo and setting up the proper `.env` file (copying `.env.example` and updating the values like getting the token as per the wiki), I'm getting the following errors:

<img width="829" alt="Screenshot 2024-07-11 at 2 00 24 AM" src="https://github.com/ysdragon/StreamBot/assets/4316564/a8692909-0e3d-4231-9e7e-341fbed95878">

Hoping someone can point me in the right direction.

**Comment by ysdragon** [comment]
Please pull the repo and try to run `bun run build` again.
