### ISSUE TITLE
Hardware Acceleration not working with intel iGPU

### ISSUE THREAD

**Issue by zeocrash** [ysdragon/StreamBot#48]
I'm using the docker-compose file on my unraid server.

My server has an intel 17 13th gen with iGPU.

I've managed to get the container working but no matter what I try, i can't get hardware acceleration working.

I've set 

`STREAM_HARDWARE_ACCELERATION: "true"`

I also mapped the iGPU device in the docker compose file.
```
    devices:
      - '/dev/dri/'
```
Which works for other containers that require iGPU access (plex, handbrake)

whenever i run a stream, the video quality is poor and there is no load on the GPU (only the CPU)

I'm not sure if I'm missing some configuration item or if the docker image requires extra drivers or something.

**Comment by ysdragon** [comment]
Hi @zeocrash, 
Can you try to install and run the bot without docker compose to check if the hardware accel is working?

**Comment by zeocrash** [comment]
Sure I'll give it a try later

**Comment by zeocrash** [comment]
I installed it on my local machine using bun and it ran with hardware acceleration.

That shows that hardware acceleration in general is working but doesn't rule out compatibility issues with intel iGPU as my local machine has an NVidia card not an intel iGPU.

I can't install it without docker on unraid as it doesn't support that.

**Comment by ysdragon** [comment]
Hello zeocrash, thank you for letting me know.
You can try to modify the docker image to support the iGPU drivers first.
I will close this issue now, if you have any further question/issue, please open a new issue.
