### ISSUE TITLE
Can we force the bot to play the highest youtube resolution ? 

### ISSUE THREAD

**Issue by Al-Rashed** [ysdragon/StreamBot#49]
How I can make it choose highest resolution ? as it choose a bad resolution ?

**Comment by ysdragon** [comment]
This feature not included in the bot, it will be added in the future.

**Comment by Al-Rashed** [comment]
> This feature not included in the bot, it will be added in the future.

Do you have an estimation ? when it will be released ? 
جزاك الله خير

**Comment by Al-Rashed** [comment]
The same my friend its not choosing the highest quality

**Comment by ysdragon** [comment]
Tested already, And it gives me the highest quality.
Try to change the bitrate to a higher value and check again.

**Comment by Al-Rashed** [comment]
services:
  streambot:
    image: quay.io/ydrag0n/streambot:latest
    container_name: streambotold
    restart: always
    environment:
      # Selfbot options
      TOKEN: "MlV-hdhVbcACefs4" # Your Discord self-bot token
      PREFIX: "!" # The prefix used to trigger your self-bot commands
      GUILD_ID: "97025700" # The ID of the Discord server your self-bot will be running on
      COMMAND_CHANNEL_ID: "1272177826" # The ID of the Discord channel where your self-bot will respond to commands
      VIDEO_CHANNEL_ID: "1199415365" # The ID of the Discord voice/video channel where your self-bot will stream videos
      VIDEOS_FOLDER: "./videos" # The local path where you store video files
      PREVIEW_CACHE: "/tmp/preview-cache" # The local path where your self-bot will cache video preview thumbnails

      # Stream options
      STREAM_WIDTH: "2560" # The width of the video stream in pixels
      STREAM_HEIGHT: "1440" # The height of the video stream in pixels
      STREAM_FPS: "30" # The frames per second (FPS) of the video stream
      STREAM_BITRATE_KBPS: "10000" # The bitrate of the video stream in kilobits per second (Kbps)
      STREAM_MAX_BITRATE_KBPS: "2000000" # The maximum bitrate of the video stream in kilobits per second (Kbps)
      STREAM_HARDWARE_ACCELERATION: "true" # Whether to use hardware acceleration for video decoding, set to "true" to enable, "false" to disable
      STREAM_VIDEO_CODEC: "H264" # The video codec to use for the stream, can be "H264" or "H265" or "VP8"

      # Videos server options
      SERVER_ENABLED: "true" # Whether to enable the built-in video server
      SERVER_USERNAME: "alrashed" # The username for the video server's admin interface
      SERVER_PASSWORD: "11" # The password for the video server's admin interface
      SERVER_PORT: "8080" # The port number the video server will listen on
    volumes:
      
./videos:/home/bots/Streambot/videos
  ports:
3000:3000

**Comment by ysdragon** [comment]
There's no 10000, and 2000000, maximum is 8000.

**Comment by Al-Rashed** [comment]
> There's no 10000, and 2000000, maximum is 8000.

Same my brother

**Comment by ysdragon** [comment]
I think it's a problem from your side, because i don't have such issue.
