### ISSUE TITLE
Async Stream (Audio/Video)

### ISSUE THREAD

**Issue by Abruccii** [ysdragon/StreamBot#58]
Issue: Audio and Video are out of Sync (Audio is ~ 1sec earlier)
Issue happens when playing .mkv files via. play command (play ./movies/test.mkv)

File Info:
Name: test.mkv
Res: 1920x800
FPS: 23.98
Format/Codec: h264 | matroska,webm

Any idea how to fix that?

**Comment by boardjoker** [comment]
have the same issue

**Comment by Abruccii** [comment]
> have the same issue

do you use ffmpeg from jellyfin server or have you installed ffmpeg normally?
i had desync issues with the custom ffmpeg build from jellyfin

**Comment by ysdragon** [comment]
Seems like it's an issue from `dank074/Discord-video-stream` package

**Comment by Abruccii** [comment]
Issue regards custom ffmpeg solution by jellyfin. Using normal ffmpeg installation with enableNativeFPS: false works.
So issue can be closed
