### ISSUE TITLE
Please add a cache disable option

### ISSUE THREAD

**Issue by egornovivan** [ysdragon/StreamBot#61]
Since v1.0.9, long videos are very problematic to play. Please add a parameter to disable the cache or return docker v1.0.8

**Comment by ysdragon** [comment]
Yes, i will add this option soon.

**Comment by ysdragon** [comment]
Hi @egornovivan,
Added in this [commit](https://github.com/ysdragon/StreamBot/commit/701a9135bb99a527f33470038fbe5ccc809c80a0)
