### ISSUE TITLE
Can't Start on Ubuntu

### ISSUE THREAD

**Issue by Algerization** [ysdragon/StreamBot#65]
I recently tried to run the bot on WSL and it gives some errors: "UNC paths are not supported.  Defaulting to Windows directory."
![image](https://github.com/user-attachments/assets/3d4b5b32-d845-436a-9486-b07a243afc68)

The bot works perfectly fine on Windows, I tried to Build the bot using Ubuntu only but its always gives the same issue.

**Comment by ysdragon** [comment]
Can you try running `bun dist/index.js`? I have tested the bot under WSL before, and it was working perfectly. If you want to run the bot under Linux, you could try running it in a Linux VM using VirtualBox, VMware, etc.
I will close this issue now. If you have any further questions, please open a new one.

**Comment by Algerization** [comment]
![image](https://github.com/user-attachments/assets/cab60063-8cdd-4896-a77f-f450ebab496f)

Trying to run using bun ./dist/index.js
