### ISSUE TITLE
Selfbot response

### ISSUE THREAD

**Issue by JQNorman** [ysdragon/StreamBot#69]
Hello there, I am testing selfbot currently and noticed it does not respond to itself. Is there a way I can test it without another person/bot user used and just using my self token temporarily?

**Comment by ysdragon** [comment]
Hi @JQNorman,
If you want to do that, you risk having your Discord account banned. If you really want to proceed, just delete/comment this [line](https://github.com/ysdragon/StreamBot/blob/a92d3481b8bd558309daeef80e678513eb1d8b12/src/index.ts#L133C6-L133C79).
