### ISSUE TITLE
ELIFECYCLE Command failed. 

### ISSUE THREAD

**Issue by Blendi87** [ysdragon/StreamBot#70]
with today's version I get the “ELIFECYCLE Command failed.” After the selfbot has started the stream.

The bot is rebuilt every time with the Dockerfile and the latest “git” data from me.

The last version was asynchronous and stopped videos in the middle.

Thanks for your hard work anyway :)

**Comment by ysdragon** [comment]
> with today's version I get the “ELIFECYCLE Command failed.” After the selfbot has started the stream.

I don't have such an issue.

> The bot is rebuilt every time with the Dockerfile and the latest “git” data from me.

Yes, if I understand correctly, the Docker image is built with every push to the repository. In the future, I may only build the Docker image for each release..
