### ISSUE TITLE
Stream not showing Video

### ISSUE THREAD

**Issue by DJChrisMas** [ysdragon/StreamBot#71]
Im trying to give as much info as possible.
I installed the Source on my proxmox 7.4 Server and in an Ubuntu VM running on the Proxmox Server:
Both installs had an issue a few days back: When trying to play a youtube video or a local .mp4 ffmpeg would throw an Error:
"ffmpeg exited with code: 1" Without any more additional information (sadly). I was figuring it was probably because of some missing dependencies but couldn't be bothered to dig deeper. 

Transcoding a video with ffmpeg works as expected and does not throw an error.

Then with the recently updated version of StreamBot I downloaded today the Error is gone (yay) but the Bot still doesn't put out any video in the discord stream.
The bot joins the correct channel and starts a stream, it just doesn't load at all.

Running on a 
R9 5900X and Nvidia Tesla P4 combo on proxmox
or with 4 5900X Cores on a Ubuntu VM (no GPU passthrough) 

Neither hw accelerated or the software decoding setting change something at the outcome.

Im kinda stuck since im not getting any errors from the running program.
Any help is appreciated, or just close the issue if im just missing something.

**Comment by ysdragon** [comment]
Can you try the Docker image using Docker Compose first?
Check the [Docker Compose section](https://github.com/ysdragon/StreamBot?tab=readme-ov-file#start-with-docker-compose)

**Comment by DJChrisMas** [comment]
Okay, thank you for your quick reply.

so I missed you replacing bun with nodejs 21 (and up). 

Running in Docker Composure still does not work for me (and the webinterface refuses the connection after trying to log in)
BUT after reinstalling everything + installing nodejs the Bot now works on baremetal proxmox 7.4
Which is good enough for me.

After I reinstalled everything I gave Docker a try again, and this time the webinterface works perfectly fine but still no luck streaming.

You can close the issue now I guess
And Thank you again

**Comment by ysdragon** [comment]
If you have any further questions, please feel free to open a new issue.
