### ISSUE TITLE
Container core dumps trying to play a Video

### ISSUE THREAD

**Issue by CooperWallace** [ysdragon/StreamBot#72]
I've tried a few times now to play a variety of files, only for the program to run into a Core Dump.

```
> streambot@1.1.0 start
> node ./dist/index.js

Available videos:
Test
(node:74) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Server is running on port 3000
--- snip-- is ready ---
Started playing video
Playing ( Test )...
Segmentation fault (core dumped)
```

I'm running Docker version 24.0.7, build 24.0.7-0ubuntu2~22.04.1.

**Comment by CooperWallace** [comment]
I'm running the same compose file as the one offered in the repo. Bot joins the server, and begins to play video. However No video shows up. Happens with both local files and youtube ones.

**Comment by ysdragon** [comment]
@CooperWallace what's the nodejs version you have?

**Comment by ysdragon** [comment]
> I'm running the same compose file as the one offered in the repo. Bot joins the server, and begins to play video. However No video shows up. Happens with both local files and youtube ones.

Please try again now.

**Comment by CooperWallace** [comment]
That definitely solved the problem for me! Thank you!

**Comment by ysdragon** [comment]
Good news!
I can close this issue now. If you have any further questions, please consider opening a new issue.
