### ISSUE TITLE
Only Stream a Url video 

### ISSUE THREAD

**Issue by matheusaudibert** [ysdragon/StreamBot#76]
## Hello, im looking for a code that just: receive a yturl and a call id (can be changed on code, withot using chat comands) then the selfbot enters and start streaming, without the pause or anithyng else. Could u guys launch it? With only 1 file?

**Comment by ysdragon** [comment]
Like a static YouTube URL with a static channel, and when starting the bot it will start with these options?

**Comment by matheusaudibert** [comment]
Yess, im making a SELF AI BOT. You request something to it, like "Play Gods Plan form Drake", the trained ai will search it on youtube and returns me the URL VIDEO (https://www.youtube.com/watch?v=xpVfcZ0ZcFM), then I want to run the script to play the video, with the url provided.

**Comment by matheusaudibert** [comment]
> Like a static YouTube URL with a static channel, and when starting the bot it will start with these options?

Hi?
