### ISSUE TITLE
[ERROR]: Installation & build fails

### ISSUE THREAD

**Issue by phere-x** [ysdragon/StreamBot#8]
OS: `Ubuntu 20.04.6 LTS` (a VM on proxmox)

Executing `npm i` gives: [nmp i.txt](https://github.com/ysdragon/StreamBot/files/13432910/nmp.i.txt)

executing `npm run build`:
```
$ npm run build

> StreamBot@1.0.4 build /data/sbot
> npx tsc

Unexpected token ?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! StreamBot@1.0.4 build: `npx tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the StreamBot@1.0.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sv/.npm/_logs/2023-11-22T02_36_21_994Z-debug.log
```

log file: [2023-11-22T02_36_21_994Z-debug.log](https://github.com/ysdragon/StreamBot/files/13432922/2023-11-22T02_36_21_994Z-debug.log)

**Comment by ysdragon** [comment]
You are using an old version of Node.js and npm (`10.19.0, 6.14.4`). You should read our README before opening this issue because I mentioned there that the minimum supported version of Node.js is `16.9.0` or later.
